/*
 * Annpurna API
 * Annpurna - Cli Web Services.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: atri.avneesh@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package org.annpurna.wallet.cli.api.model;
/** Custom Model Class **/
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.math.BigDecimal;
import javax.validation.constraints.*;

/** This is custom pojo template generated file
 * Tx
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaJerseyServerCodegen", date = "2021-12-19T23:11:31.868+05:30")
public class Tx   {
  @JsonProperty("senderWalletId")
  private String senderWalletId = null;

  @JsonProperty("senderSecret")
  private String senderSecret = null;

  @JsonProperty("recipientWalletId")
  private String recipientWalletId = null;

  @JsonProperty("amount")
  private BigDecimal amount = null;

  public Tx senderWalletId(String senderWalletId) {
    this.senderWalletId = senderWalletId;
    return this;
  }

  /**
   * Get senderWalletId
   * @return senderWalletId
   **/
  @JsonProperty("senderWalletId")
  @ApiModelProperty(value = "")
  public String getSenderWalletId() {
    return senderWalletId;
  }

  public void setSenderWalletId(String senderWalletId) {
    this.senderWalletId = senderWalletId;
  }

  public Tx senderSecret(String senderSecret) {
    this.senderSecret = senderSecret;
    return this;
  }

  /**
   * Get senderSecret
   * @return senderSecret
   **/
  @JsonProperty("senderSecret")
  @ApiModelProperty(value = "")
  public String getSenderSecret() {
    return senderSecret;
  }

  public void setSenderSecret(String senderSecret) {
    this.senderSecret = senderSecret;
  }

  public Tx recipientWalletId(String recipientWalletId) {
    this.recipientWalletId = recipientWalletId;
    return this;
  }

  /**
   * Get recipientWalletId
   * @return recipientWalletId
   **/
  @JsonProperty("recipientWalletId")
  @ApiModelProperty(value = "")
  public String getRecipientWalletId() {
    return recipientWalletId;
  }

  public void setRecipientWalletId(String recipientWalletId) {
    this.recipientWalletId = recipientWalletId;
  }

  public Tx amount(BigDecimal amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   **/
  @JsonProperty("amount")
  @ApiModelProperty(value = "")
  public BigDecimal getAmount() {
    return amount;
  }

  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Tx tx = (Tx) o;
    return Objects.equals(this.senderWalletId, tx.senderWalletId) &&
        Objects.equals(this.senderSecret, tx.senderSecret) &&
        Objects.equals(this.recipientWalletId, tx.recipientWalletId) &&
        Objects.equals(this.amount, tx.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(senderWalletId, senderSecret, recipientWalletId, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Tx {\n");
    
    sb.append("    senderWalletId: ").append(toIndentedString(senderWalletId)).append("\n");
    sb.append("    senderSecret: ").append(toIndentedString(senderSecret)).append("\n");
    sb.append("    recipientWalletId: ").append(toIndentedString(recipientWalletId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
